stages:
  - build
  - deploy

image: node:13.10.1-stretch

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn
    - yarn build

deploy_dev:
  before_script:
    - npm install -g firebase-tools
  stage: deploy
  environment: Development
  script:
    - firebase use $FIREBASE_DEPLOY_NAME_DEV --token $FIREBASE_DEPLOY_KEY
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_DEPLOY_KEY