# version docker compose
version: '3.7'
services:
  app:
    stdin_open: true
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev # development
    volumes:
      - '.:/app'
      - '/app/node_modules' # necessary to not overwrite the build dir.
    ports:
      - '3001:80'
    environment:
      - NODE_ENV=development
      - CI=true
