# version docker compose
version: '3.7'
services:
  app:
    stdin_open: true
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules' # nescessário para não sobrescrever o dir do build
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CI=true
