# version docker compose
version: '3.3'

services:
  app:
    image: nexus.devops.ifrn.edu.br/{{ repository|lower }}:latest
    restart: always
    stdin_open: true
    volumes:
      - '.:/app'
      - '/app/node_modules' # necessary to not overwrite the build dir.
    ports:
      - '{{ port }}:80'
    environment:
      - NODE_ENV=development
      - REACT_APP_FACEBOOK_APP_ID=$CI_REACT_APP_FACEBOOK_APP_ID
      - REACT_APP_GOOGLE_CLIENT_ID=$CI_REACT_APP_GOOGLE_CLIENT_ID
      - CI=true
